### ISSUE TITLE
What is the benefit to convert data in feathers to vuex instead of accessing feathers services directly?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-vuex#18]
This question might be silly, but I wonder what is the benefit to convert data in feathers to vuex instead of accessing feathers services directly?

**Comment by ellipticaldoor** [comment]
I think that in this way you have more flexibility and reusability, so your app is going to be faster doing less calls to feathers.

Also in vue if you have a lot of components that need to communicate between them vuex is one of the best options, this library makes life a lot easier.

**Comment by ndamjan** [comment]
I would also add that you remove a lot of boilerplate and state management needed for every service you are using.

**Comment by beeplin** [comment]
Got it. I was previously thinking of using client-side feathers service as front-end data hub, and rxjs (with feathers-rx and vue-rx) as reactive system to connect feathers data and vue components. For feathers users this might be a more straightforward way to achieve the same goal of Vuex.

Will keep tracking this repo. ;)

**Comment by marshallswain** [comment]
Yep!  Sharing state between components was the primary reason for needing vuex.  Eliminating boilerplate while enforcing "best practices" under the hood was my motivation for creating `feathers-vuex`.   It also has feathers-memory built into the vuex store, so you can perform queries with the Feathers query language against the local data that you have already pulled down from the server.  And it's cool to watch Vue's reactivity automatically update the data in your local queries when feathers-reactive updates the data in the store with remote data.
