### ISSUE TITLE
removeItems action added after create when upgrading version from version 0.4.0 to 0.4.1

### ISSUE THREAD

**Issue by japie1001** [feathersjs/feathers-vuex#19]
When creating an action with:
 this.createMessage({'text': 'some message'})

I expect a new message to be added to the store.

This happens in version 0.4.0, but after upgrading to 0.4.1 there is an additional unwanted action added: messages/removeItems

This makes the state for the messages module 0, which is unexpected and undesirable behaviour.

How can I resolve this issue?

**Module versions** (especially the part that's not working): feathers-vuex 0.4.0 - 0.4.1
**NodeJS version**: v6.10.2
**Operating System**: Windows 8.1
**Browser Version**: Chrome Version 58.0.3029.110 (64-bit)
**React Native Version**: not applicable.
**Module Loader**: webpack

**Comment by marshallswain** [comment]
For now, just go back to the version before this feature was added.

`npm install feathers-vuex@0.3.1`.
