### ISSUE TITLE
Weird / destructive behaviour using mapActions service find between components

### ISSUE THREAD

**Issue by ellipticaldoor** [feathersjs/feathers-vuex#21]
I'm having a weird behaviour using find, this is how I'm using it:

I'm using feather-vuex 0.4.2, I also tried 0.3.1 and I get the same result.

## **First component**
On the first component I do a **find** without a query, it returns all the results and store them on vuex.
``` js
methods: {
	...mapActions('profiles', { findProfiles: 'find' }),

	fetch() {
		this.findProfiles({})
	},
},

created() {
	this.fetch()
},
```
Screenshot of Vuex state after find:
<img width="201" alt="screen shot 2017-06-09 at 10 40 13" src="https://user-images.githubusercontent.com/3449006/26971090-b9775324-4d03-11e7-9adf-18576ae70bab.png">

## **Second component**
Now I do a **get** and after it the results fetched with the find are still in the store. Everything is fine here.
``` js
methods: {
	...mapActions('profiles', { getProfile: 'get' }),

	fetch() {
		this.getProfile(this.user.profile)
	},
},

created() {
	this.fetch()
},
```
<img width="213" alt="screen shot 2017-06-09 at 11 06 24" src="https://user-images.githubusercontent.com/3449006/26971295-80a93d90-4d04-11e7-81c4-082c44b30b17.png">

## **Third component**
Now I do other **find** but with a custom query, I just want to find an element, the query works fine but it destroy the results of the first find  :(
``` js
methods: {
	...mapActions('profiles', { findProfile: 'find' }),

	fetch() {
		this.findProfile({
			query: { slug: this.$route.params.slug },
		})
	},
},

created() {
	this.fetch()
},
```
<img width="202" alt="screen shot 2017-06-09 at 11 10 29" src="https://user-images.githubusercontent.com/3449006/26971301-842c67e4-4d04-11e7-99fa-3df974c18d18.png">

Is this a bug or the expected behaviour? I'm missing something?

**Comment by victorm95** [comment]
This is the expected behavior, the store relfect the result of the actions, if your action only get 1 object your store will have 1 object.
You can use the getter, but the getters only search in the store, not in the server. So you can use the action `find` without query for get all the objects and then use the getter `find` with query for filter the result.
Or use feathers directly, that way the store doesn't change.

You can see how combine the action and getter in the [feathers chat vuex](https://github.com/feathersjs/feathers-chat-vuex).

##### Sorry for my English.

**Comment by ellipticaldoor** [comment]
Okey, but if I already downloaded some info and I know that I don't need to fetch it again from the server why I have to do it again?

**Comment by victorm95** [comment]
Yeah, if you know that the action `find` was call before, just use the getters.
But if you need paginate the results you have to use the actions.

**Comment by marshallswain** [comment]
Sorry, I've been gone for a few days.  This behavior could be expected with the 0.4 version of the plugin, but previous versions do not handle any removing of records, as far as I remember.  Each query to `find` should be completely independent, and their results should only add to the store.  @ellipticaldoor have you been able to set some breakpoints to see where the results are getting removed in the 0.3 version?  I would think that downgrading would have fixed the issue.

**Comment by ellipticaldoor** [comment]
I tried again version 0.3.0 and 0.3.1 and now all the data persists :D

Probably I didn't removed correctly the 0.4.2.

I still have to learn how to use breakpoints...

**Comment by marshallswain** [comment]
Thanks for reporting back.  It will take me some time to figure out a solution.
