### ISSUE TITLE
React Native   not working if remove data

### ISSUE THREAD

**Issue by agungid** [feathersjs/feathers-vuex#39]
Hi. I have a problem in Service Actions. When doing remove items, it does not seem to  `commit ('removeItem', id)` . No changes to getters in different browsers
![reactive](https://user-images.githubusercontent.com/11351024/29244320-c02968ec-7fdf-11e7-9553-f324e8af5b29.png)

Thank you

**Comment by jskrzypek** [comment]
@agungid you're not supposed to `commit` the mutations directly, as they do not invoke the service (see [`src/service-module/mutations.js`](https://github.com/feathersjs/feathers-vuex/blob/master/src/service-module/mutations.js#L46-L58))

You should be doing a `dispatch('remove', id)` which calls the remove action instead. This will call the service which will update other connected clients: (see [`src/service-module/actions.js`](https://github.com/feathersjs/feathers-vuex/blob/master/src/service-module/actions.js#L110-L125))

**Comment by agungid** [comment]
@jskrzypek  I've done it on service action. Such as opted in
` methods: {
        ...mapActions('customers', {
            findCustomers: 'find',
            createCustomer: 'create',
            updateCustomer: 'patch',
            removeCustomer: 'remove'
        }),

        deleteCustomer(id) {
            this.removeCustomer(id)
        },
    }`

But this does not work for other clients

**Comment by marshallswain** [comment]
@gungid, could you try upgrading to the latest pre-release?  I think it may resolve some of your issues.  See details here: https://github.com/feathersjs/feathers-vuex/issues/40.

**Comment by agungid** [comment]
I try to update it first with version 1.0. Thank you for your response
